/* eslint-disable */
/**
 * BrainNetworkViewer.jsx
 * ======================
 * SIGGRAPH 2026 — Real-time fMRI Brain Network Renderer
 *
 * Stack  : React Three Fiber (@react-three/fiber), Three.js, @react-three/drei
 * Data   : network_data.json (generated by generate_fdeb.py → /public/)
 *
 * What happens here
 * -----------------
 *  1. Load JSON (nodes + bundled FDEB splines).
 *  2. Render each node as a small semi-transparent sphere (color = region).
 *  3. Reconstruct each spline with THREE.CatmullRomCurve3 and render it
 *     using a TubeGeometry driven by a custom GLSL ShaderMaterial.
 *  4. A single u_time uniform ticks every frame.  Inside the shader the
 *     per-tube t_peak_src / t_peak_tgt are encoded as vertex attributes so
 *     the GPU computes the "HRF pulse wave" per fragment with zero CPU cost.
 *
 * Usage
 * -----
 *  import BrainNetworkViewer from './BrainNetworkViewer';
 *  // Render anywhere:  <BrainNetworkViewer />
 *
 * Dependencies (package.json)
 * ---------------------------
 *  @react-three/fiber   ^8
 *  @react-three/drei    ^9
 *  three                ^0.163
 */

import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls } from '@react-three/drei';
import * as THREE from 'three';

// ── Region → neon colour map ───────────────────────────────────────────────
const REGION_COLORS = {
  V1: '#ff2dca', // magenta
  V2: '#ff8c00', // amber
  V3: '#00e5ff', // cyan
  V4: '#39ff14', // neon green
};

// ═══════════════════════════════════════════════════════════════════════════
// GLSL SHADER — HRF Pulse Wave
// ═══════════════════════════════════════════════════════════════════════════
//
// VERTEX SHADER
//   We interpolate the t_peak value linearly along the tube (a_tPeakSrc at
//   the start, a_tPeakTgt at the end) using the built-in UV.x coordinate
//   which Three.js TubeGeometry maps to [0, 1] along the length of the tube.
//
// FRAGMENT SHADER
//   For each fragment we know v_tPeak — the expected BOLD peak time at that
//   location.  We compute a Gaussian bell centred on that time:
//
//     pulse(t, tPeak) = exp( -(t - tPeak)² / (2σ²) )
//
//   where σ controls the temporal spread of the glow.
//   The loop period PERIOD means u_time is wrapped with mod() so the
//   animation loops seamlessly.  Full opacity + brightness only when the
//   global clock aligns with local t_peak (simulating a blood-flow wave
//   sweeping from V1 → V4).
//
//   The constant base alpha keeps the tubes faintly visible at rest (ghost
//   view), while the pulse term spikes to 1.0 during the "active" window.

const VERT = /* glsl */ `
  // Per-vertex t_peak values set via BufferAttribute
  attribute float a_tPeakSrc;
  attribute float a_tPeakTgt;

  // Passed to fragment shader
  varying float v_tPeak;
  varying vec2  v_uv;

  void main() {
    // uv.x: 0 at tube start (source), 1 at tube end (target)
    // Linear interpolation along the spline gives a smooth t_peak gradient.
    v_tPeak = mix(a_tPeakSrc, a_tPeakTgt, uv.x);
    v_uv    = uv;

    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  }
`;

const FRAG = /* glsl */ `
  precision highp float;

  uniform float u_time;      // global clock (seconds), incremented each frame
  uniform vec3  u_color;     // base neon colour of this tube
  uniform float u_period;    // animation loop period (seconds)
  uniform float u_sigma;     // Gaussian temporal width (seconds)

  varying float v_tPeak;
  varying vec2  v_uv;

  void main() {
    // Wrap time so the pulse wave repeats every u_period seconds.
    float t      = mod(u_time, u_period);

    // ── HRF Gaussian pulse ──────────────────────────────────────────────
    // pulse ∈ [0, 1]: peaks to 1.0 exactly when t == v_tPeak.
    // σ  (u_sigma) controls how sharp or diffuse the glow appears.
    // Larger σ → wider, softer glow;  smaller σ → sharp blip.
    float delta  = t - v_tPeak;
    float pulse  = exp(-(delta * delta) / (2.0 * u_sigma * u_sigma));

    // ── Composite alpha ─────────────────────────────────────────────────
    // BASE_ALPHA : the tube is always faintly visible (ghost / context view)
    // The pulse term spikes it to ~1.0 during the activation window.
    float BASE_ALPHA = 0.28;   // 항상 보이는 기본 투명도 (높을수록 선명)
    float alpha  = BASE_ALPHA + (1.0 - BASE_ALPHA) * pulse;

    // ── Brightness boost ────────────────────────────────────────────────
    // Bloom-like: multiply colour toward white at peak, deep hue at rest.
    vec3  col    = mix(u_color, vec3(1.0), pulse * 0.55);

    gl_FragColor = vec4(col, alpha);
  }
`;

// ═══════════════════════════════════════════════════════════════════════════
// BundledEdge — a single animated TubeGeometry driven by the shader
// ═══════════════════════════════════════════════════════════════════════════
function BundledEdge({ edge, regionColor }) {
  const matRef = useRef();

  // Build geometry + material together so uniforms are always in sync
  const { geometry, material } = useMemo(() => {
    const pts = edge.control_points.map(
      ([x, y, z]) => new THREE.Vector3(x, y, z)
    );

    const curve = new THREE.CatmullRomCurve3(pts, false, 'catmullrom', 0.5);
    const TUBE_SEGS = 48;
    const geo = new THREE.TubeGeometry(curve, TUBE_SEGS, 0.022, 6, false);

    // Per-vertex t_peak attributes for the vertex shader
    const vertCount = geo.attributes.position.count;
    const srcArr = new Float32Array(vertCount).fill(edge.t_peak_src);
    const tgtArr = new Float32Array(vertCount).fill(edge.t_peak_tgt);
    geo.setAttribute('a_tPeakSrc', new THREE.BufferAttribute(srcArr, 1));
    geo.setAttribute('a_tPeakTgt', new THREE.BufferAttribute(tgtArr, 1));

    // Create ShaderMaterial directly — no extend() needed, no JSX prop mapping issues
    const mat = new THREE.ShaderMaterial({
      vertexShader:   VERT,
      fragmentShader: FRAG,
      transparent:    true,
      depthWrite:     false,
      blending:       THREE.AdditiveBlending,
      uniforms: {
        u_time:   { value: 0 },
        u_color:  { value: new THREE.Color(regionColor) },
        u_period: { value: 10.0 },
        u_sigma:  { value: 1.1 },
      },
    });

    return { geometry: geo, material: mat };
  }, [edge, regionColor]);

  // Tick u_time every frame — only this uniform changes, geometry is static
  useFrame(({ clock }) => {
    material.uniforms.u_time.value = clock.getElapsedTime();
  });

  return <mesh geometry={geometry} material={material} />;
}

// ═══════════════════════════════════════════════════════════════════════════
// Scene — loads JSON and assembles the full visualization
// ═══════════════════════════════════════════════════════════════════════════
function Scene() {
  const [data, setData] = useState(null);

  useEffect(() => {
    fetch('/network_data.json')
      .then(r => r.json())
      .then(setData)
      .catch(err => console.error('Failed to load network_data.json:', err));
  }, []);

  if (!data) return null;

  return (
    <group>
      {/* ── Nodes ─────────────────────────────────────────────────────── */}
      {data.nodes.map(node => (
        <mesh
          key={node.id}
          position={[node.x, node.y, node.z]}
        >
          <sphereGeometry args={[0.04, 8, 8]} />
          <meshBasicMaterial
            color={REGION_COLORS[node.region] ?? '#ffffff'}
            transparent
            opacity={0.45}
          />
        </mesh>
      ))}

      {/* ── Bundled Edges (splines + HRF shader) ─────────────────────── */}
      {data.bundled_edges.map((edge, i) => {
        // Colour the tube by the source region (V1 colour for V1→V2, etc.)
        const srcNode    = data.nodes[edge.src_id];
        const regionCol  = REGION_COLORS[srcNode?.region] ?? '#00e5ff';
        return (
          <BundledEdge
            key={i}
            edge={edge}
            regionColor={regionCol}
          />
        );
      })}
    </group>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// Legend overlay (pure HTML, outside the Canvas)
// ═══════════════════════════════════════════════════════════════════════════
function Legend() {
  const entries = [
    { region: 'V1', label: 'V1 — Primary Visual', color: REGION_COLORS.V1 },
    { region: 'V2', label: 'V2 — Secondary Visual', color: REGION_COLORS.V2 },
    { region: 'V3', label: 'V3 — Tertiary Visual', color: REGION_COLORS.V3 },
    { region: 'V4', label: 'V4 — Ventral Stream', color: REGION_COLORS.V4 },
  ];
  return (
    <div style={{
      position: 'absolute', top: 20, left: 20,
      background: 'rgba(0,0,0,0.65)',
      border: '1px solid rgba(255,255,255,0.12)',
      borderRadius: 8,
      padding: '12px 16px',
      color: '#fff',
      fontFamily: 'monospace',
      fontSize: 12,
      lineHeight: '1.9em',
      pointerEvents: 'none',
      userSelect: 'none',
    }}>
      <div style={{ fontWeight: 700, marginBottom: 6, letterSpacing: 1 }}>
        fMRI BOLD NETWORK
      </div>
      {entries.map(({ label, color }) => (
        <div key={label} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{
            width: 10, height: 10, borderRadius: '50%',
            background: color, display: 'inline-block',
            boxShadow: `0 0 6px ${color}`,
          }} />
          {label}
        </div>
      ))}
      <div style={{ marginTop: 8, opacity: 0.5, fontSize: 10 }}>
        HRF t_peak: V1 ≈ 4 s → V4 ≈ 8 s
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// Root export
// ═══════════════════════════════════════════════════════════════════════════
export default function BrainNetworkViewer() {
  return (
    <div style={{ width: '100vw', height: '100vh', background: '#000', position: 'relative' }}>
      <Legend />

      <Canvas
        camera={{ position: [0, 0, 8], fov: 55, near: 0.01, far: 100 }}
        gl={{
          antialias: true,
          // Tone-mapping off so our additive neon colours don't get clamped.
          toneMapping: THREE.NoToneMapping,
        }}
        linear   /* disable automatic sRGB gamma to keep HDR neon response */
      >
        {/* Subtle ambient so nodes aren't pitch-black in resting state */}
        <ambientLight intensity={0.15} />

        <Scene />

        {/* Mouse-drag orbit, scroll-wheel zoom */}
        <OrbitControls
          enableDamping
          dampingFactor={0.07}
          rotateSpeed={0.6}
          zoomSpeed={0.8}
          autoRotate
          autoRotateSpeed={0.4}
        />
      </Canvas>
    </div>
  );
}
